import type { ProviderDefinition } from "./types";

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude models — reasoning, code, and general purpose",
    docsUrl: "https://docs.anthropic.com",
    iconColor: "#D97757",
    supportsCustomEndpoint: false,
    models: [
      {
        id: "claude-opus-4-5-20250414",
        name: "Claude Opus 4.5",
        category: "reasoning",
        contextWindow: 200000,
        costTier: "high",
        badges: ["Reasoning", "Best"],
      },
      {
        id: "claude-sonnet-4-5-20250414",
        name: "Claude Sonnet 4.5",
        category: "general",
        contextWindow: 200000,
        costTier: "mid",
        badges: ["Balanced"],
      },
      {
        id: "claude-haiku-3-5-20241022",
        name: "Claude Haiku 3.5",
        category: "fast",
        contextWindow: 200000,
        costTier: "low",
        badges: ["Fast", "Cheap"],
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT models — multimodal, reasoning, and general purpose",
    docsUrl: "https://platform.openai.com/docs",
    iconColor: "#10A37F",
    supportsCustomEndpoint: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        category: "multimodal",
        contextWindow: 128000,
        costTier: "mid",
        badges: ["Multimodal"],
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        category: "general",
        contextWindow: 128000,
        costTier: "mid",
        badges: ["General"],
      },
      {
        id: "o1",
        name: "o1",
        category: "reasoning",
        contextWindow: 200000,
        costTier: "high",
        badges: ["Reasoning"],
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "Search-augmented models with real-time web access",
    docsUrl: "https://docs.perplexity.ai",
    iconColor: "#20808D",
    supportsCustomEndpoint: false,
    models: [
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        category: "search",
        contextWindow: 200000,
        costTier: "mid",
        badges: ["Web Search", "Citations"],
      },
      {
        id: "sonar",
        name: "Sonar",
        category: "search",
        contextWindow: 128000,
        costTier: "low",
        badges: ["Web Search", "Fast"],
      },
    ],
  },
  {
    id: "google",
    name: "Google",
    description: "Gemini models — multimodal and high-speed inference",
    docsUrl: "https://ai.google.dev/docs",
    iconColor: "#4285F4",
    supportsCustomEndpoint: false,
    models: [
      {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash",
        category: "fast",
        contextWindow: 1000000,
        costTier: "low",
        badges: ["1M Context", "Fast"],
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        category: "reasoning",
        contextWindow: 1000000,
        costTier: "high",
        badges: ["1M Context", "Reasoning"],
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    description: "European open-source models — fast and efficient",
    docsUrl: "https://docs.mistral.ai",
    iconColor: "#FF7000",
    supportsCustomEndpoint: false,
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        category: "general",
        contextWindow: 128000,
        costTier: "mid",
        badges: ["EU", "General"],
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        category: "fast",
        contextWindow: 128000,
        costTier: "low",
        badges: ["EU", "Fast"],
      },
    ],
  },
  {
    id: "custom",
    name: "Custom / Self-hosted",
    description: "Connect to Ollama, vLLM, or any OpenAI-compatible endpoint",
    docsUrl: "",
    iconColor: "#6B7280",
    supportsCustomEndpoint: true,
    models: [],
  },
];

export const getProviderById = (id: string) =>
  PROVIDER_REGISTRY.find((p) => p.id === id) ?? null;
